<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>AitApplicationDeployedVersions.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="apps.json" LogicalName="apps.json" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
